### ISSUE TITLE
Switching by number changes only for -s 0 and -s 2 but not -s 1

### ISSUE THREAD

**Issue by JezuzStardust** [myshov/xkbswitch-macosx#7] opened 2018-06-11 19:20 UTC
With two layouts in my input sources (Swedish-Pro and U.S) I get a strange behaviour. When 

`xkbswitch -s 1 `

does nothing, while 

`xkbswitch -s 0`

switches to Swedish-Pro and 

`xkbswitch -s 2`

switches to U.S. layouts. Is this behaviour expected?

**Comment by myshov** [comment] 2018-06-12 08:13
@JezuzStardust hi!
Yes that expected behaviour because of strange logic behind layouts in macOS that gives not sequential identifiers 😄
This numbers are system level identifiers of the keyboard layouts.
For example I have only Russian and English layouts. When English layout is chosen `xkbswitch -g` gives me `0`, but when Russian layout is chosen `xkbswitch -g` gives `3`.

**Comment by myshov** [comment] 2018-06-27 16:30
@JezuzStardust I am closing this issue, feel free to reopen it if you think that we need to handle this case somehow.

**Closed as completed by myshov** 2018-06-27 16:30 UTC
